snippets:
  - name: g
    keyword: g
    snippet: git

  - name: gw
    keyword: gw
    snippet: gwq

  - name: gwq list
    keyword: l
    snippet: list
    context:
      lbuffer: '^gwq\s+'

  - name: gwq remove
    keyword: rm
    snippet: remove
    context:
      lbuffer: '^gwq\s+'

  - name: gh issue
    keyword: i
    snippet: issue
    context:
      lbuffer: '^gh\s+'

  - name: gh issue/pr create
    keyword: n
    snippet: create -t '{{title}}' -b ''
    context:
      lbuffer: '^gh\s+(issue|pr)\s+'

  - name: gh issue/pr comment
    keyword: cm
    snippet: comment {{number}} -b ''
    context:
      lbuffer: '^gh\s+(issue|pr)\s+'

  - name: gh issue/pr edit
    keyword: e
    snippet: edit {{number}} -b ''
    context:
      lbuffer: '^gh\s+(issue|pr)\s+'

  - name: gh issue/pr view
    keyword: v
    snippet: view {{number}}
    context:
      lbuffer: '^gh\s+(issue|pr)\s+'

  - name: gh issue/pr close
    keyword: cl
    snippet: close {{number}} --comment ''
    context:
      lbuffer: '^gh\s+(issue|pr)\s+'

