repos:
  - repo: local
    hooks:
      - id: sanitize-email-addresses
        name: Sanitize email addresses
        entry: scripts/sanitize-email.sh
        language: script
        files: ^src/\.alias$
