#!/bin/zsh
#
# Neovim selector
# - Require: nvim, fzf
#

local nvim_dirs=( ~/.config/nvim_*(/N) )
local items=( ${nvim_dirs#*/nvim_} )
local config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config: " --height=~30% --exit-0)

if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
elif [[ $config == "default" ]]; then
    local config=""
fi

NVIM_APPNAME=nvim_$config nvim $@

