# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme


shell = "zsh"

[templates]
# Add -mpr option to prevent reset and refresh prompts (it removes RPTOMPT in starship)
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer -mpr source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fast-syntax-highlighting]
github = 'zdharma/fast-syntax-highlighting'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.starship]
inline = '''
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
export STARSHIP_CACHE=$HOME/.cache/starship
eval "$(starship init zsh)"
'''

[plugins.atuin]
inline = 'eval "$(atuin init zsh --disable-up-arrow)"'

# Add custom lazy load functions to fpath
[plugins.zsh-functions-lazy]
local = "~/.zsh/functions-lazy"
apply = ["fpath"]

# Autoload (lazy) fpath
[plugins.zsh-autoload-lazy]
inline = 'autoload -Uz $fpath[1]/*(N:t)'

# Load external configs
[plugins.zsh-configs]
local = "~/.zsh/configs"
use = ["*.zsh"]

# Lazy load external configs
[plugins.zsh-configs-lazy]
local = "~/.zsh/configs-lazy"
use = ["*.zsh"]
apply = ["defer"]

# Load external config variables and paths
[plugins.zsh-other-varpath]
inline = '''
export WALK_EDITOR=nvim
export AICOMMIT_CONFIG_PATH="$HOME/.config/aicommit2/config.ini"
export GH_PAGER='less -RFX'
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
'''

