# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$hostname\
$username\
$character\
$directory"""

right_format = """
$git_branch\
$git_status\
$python\
$rust\
$cmd_duration\
$time"""

[character]
error_symbol = '[](red)'
success_symbol = '[](green)'

[os]
disabled = false
format = "$symbol"

[os.symbols]
Macos       = "[ ](fg:green)"
Arch        = "[ ](fg:bright-blue)"
Debian      = "[ ](fg:red)"
EndeavourOS = "[ ](fg:purple)"
Fedora      = "[ ](fg:blue)"
NixOS       = "[ ](fg:bright-white)"
openSUSE    = "[ ](fg:green)"
SUSE        = "[ ](fg:green)"

[hostname]
ssh_symbol = " "
format = "[$ssh_symbol$hostname]($style): "

[username]
format = '\([$user]($style)\) '

[directory]
fish_style_pwd_dir_length = 1

[time]
disabled = false
format = " [$time](dimmed #60728a)"

[cmd_duration]
min_time = 2_000
format = "[  $duration]($style)"
style = "dimmed #60728a"

[git_branch]
symbol = " "
format = ' [$symbol$branch(:$remote_branch)](dimmed #60728a)'

[git_status]
format = '([$all_status$ahead_behind](dimmed #60728a))'

[package]

[python]
symbol = " "
style = "dimmed #60728a"
format = ' [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[rust]
symbol = " "
style = "dimmed #60728a"
format = ' [$symbol($version)]($style)'
